# Name of website
theme: jekyll-theme-midnight

#Site settings
locale                   : "en-CA"
title                    : "Eric Hagen, PhD"
title_separator          : "-"
name                     : "Eric Hagen"
description              : "Postdoctoral Fellow, University of Toronto"
url                      : "https://erichagen.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "EricHagen/erichagen.github.io"
teaser                   : #/assets/images/tortle.jpeg" #500x300
logo                     : "/assets/images/tortle.jpeg" #88x88
masthead_title           : "Eric Hagen"

#Social media
social-network-links:
  email: "eric.hagen@utoronto.ca"
  rss: false
  twitter: EricHagen19
